### ISSUE TITLE
[Memory Leak] Members does not get cleared when leaving

### ISSUE THREAD

**Issue by wzrdtales** [rjrodger/sneeze#16]
Members will always leave some non existing references behind, as swim removes the handlers before all timeOuts are being handled.

https://github.com/rjrodger/sneeze/blob/295c83310e3f094b09100343de5b37227e5b03e2/sneeze.js#L235

There is no reset of members on the site of sneeze, so we have a memory leak here.

**Comment by rjrodger** [comment]
fixed via pr
