### ISSUE TITLE
Needs finer-grained updates to node statuses

### ISSUE THREAD

**Issue by avishnyak** [rjrodger/sneeze#7]
Based on my testing, the following code could lead to a node being added twice by a client of the library.  In some cases, I am seeing new nodes come online and trigger both a Change and an Update (for example, this is happens in the https://github.com/rjrodger/seneca-mesh client)

```javascript
        swim.on(Swim.EventType.Update, function onUpdate(info) {
          updateinfo(info)
        })

        swim.on(Swim.EventType.Change, function onChange(info) {
          updateinfo(info)
        })
```

Repro using https://github.com/rjrodger/seneca-mesh (using separate terminals):

1. node base.js
1. node service-bar.js (first instance)
1. node service-bar.js (second instance)
1. node service-foo.js
1. kill the second instance of service-bar.

Expected result: service-foo.js only sends messages to the first instance of service-bar.js after sneeze notifies it of a dead node.

Actual Result: service-foo.js continues to try and send messages to the second instance of service-bar.js because it has added two identical entries for service-foo to its load balancer.

**Comment by rjrodger** [comment]
agreed

**Comment by rjrodger** [comment]
this is now fixed
